import type {
  GenerateStructuredInput,
  GenerateStructuredResult,
  TextGenerationProvider,
} from '@/lib/ai/provider';

/**
 * Mock AI Provider for local testing without spending OpenAI credits.
 * Enabled when `ENABLE_MOCK_AI=true` or `STORAGE_DRIVER=memory` with mock key.
 */
export class MockAiProvider implements TextGenerationProvider {
  readonly name = 'mock';
  readonly model = 'mock-gpt-4o';
  readonly isConfigured = true;

  async generateStructured(input: GenerateStructuredInput): Promise<GenerateStructuredResult> {
    const startedAt = Date.now();

    // Generate mock structured suggestions based on input document content
    const raw = {
      summary: 'Automated analysis summary generated by local Mock AI Provider.',
      actions: [
        {
          title: 'Review document specifications and requirements',
          description: 'Ensure all specifications extracted from the uploaded document are verified.',
          assigneeName: null,
          dueDate: null,
          priority: 'MEDIUM',
          confidence: 0.95,
          evidence: input.user.slice(0, 100) || 'Sample document content quote.',
          sourceLocation: 'Page 1',
          actionType: 'TASK',
        },
        {
          title: 'Confirm team action items and deadlines',
          description: 'Follow up with stakeholders on action items identified during review.',
          assigneeName: null,
          dueDate: null,
          priority: 'HIGH',
          confidence: 0.9,
          evidence: input.user.slice(100, 200) || 'Follow up required for next steps.',
          sourceLocation: 'Page 1',
          actionType: 'FOLLOW_UP',
        },
      ],
    };

    return {
      raw,
      model: this.model,
      usage: {
        promptTokens: 150,
        completionTokens: 80,
        totalTokens: 230,
      },
      durationMs: Date.now() - startedAt,
    };
  }
}
